name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - run: |
          sudo apt-get install -y libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang cmake make libprotobuf-dev protobuf-compiler
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with: 
          toolchain: 1.77.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - uses: ncipollo/release-action@v1
        with:
          artifacts: target/release/atlas_txn_sender
          omitBody: true
          token: ${{ secrets.GITHUB_TOKEN }}

